name: Dang Ky Com Hang Ngay

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install Libraries
        run: pip install -r requirements.txt
      - name: Run Auto Tool
        run: python main.py
      
      # --- THÊM ĐOẠN NÀY ĐỂ TẢI ẢNH VỀ ---
      - name: Upload Screenshot
        if: always() # Luôn chạy dù lỗi hay không
        uses: actions/upload-artifact@v3
        with:
          name: bang-chung-chup-man-hinh
          path: evidence.png
