name: Dang Ky Com Hang Ngay

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Đã nâng cấp lên v4
      - name: Setup Python
        uses: actions/setup-python@v5 # Đã nâng cấp lên v5
        with:
          python-version: '3.9'
      - name: Install Libraries
        run: pip install -r requirements.txt
      - name: Run Auto Tool
        run: python main.py
      
      # --- ĐOẠN NÀY ĐÃ SỬA TỪ v3 SANG v4 ---
      - name: Upload Screenshot
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: bang-chung-chup-man-hinh
          path: evidence.png
